### ISSUE TITLE
Splitter does not work in a horizontal fashion

### ISSUE THREAD

**Issue by fabitamas** [tejainece/webide_splitter#1]
I can't seem to figure out how to use the splitter in a horizontal fashion.
I tried to set flex-direction: column; and used the following css
definition for .panel:

.panel {
  width: 100%;
  height: calc((100% - 14px) / 3);
}

I end up with what you can see in the attachment.

<img width="1404" alt="screen shot 2018-01-01 at 6 08 09 pm" src="https://user-images.githubusercontent.com/5854373/34529857-4953b648-f07b-11e7-8287-ec5721a33d2a.png">

**Comment by tejainece** [comment]
Working on it

**Comment by tejainece** [comment]
Fixed by https://github.com/tejainece/webide_splitter/commit/d88fffe002cdb8308e9cb0a0121f638725e7b069

Also fixed jitter.

Reopen if you find problem. Also added examples and better README.
